version: '3'
services:
  nodejs-server:
    hostname: nodejs-server
    image: sudhakary/node_backend:latest
    entrypoint: ["npm", "start"]
    ports:
      - "3000:3000"
  angular-ui:
    hostname: angular-ui
    ports:
      - "4200:4200"
    image: sudhakary/angular_web:latest
    depends_on: 
      - nodejs-server
    entrypoint: ["ng", "serve","--host", "0.0.0.0", "--port", "4200"]

