# base image
FROM node:10.19.0-alpine AS build

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@7.3.9

# add app
COPY . /app

# start app
#CMD ng serve --host 0.0.0.0
RUN npm run build
### STAGE No 2: Run ###
FROM nginx:1.17.1-alpine
COPY --from=build /app/dist/newproject /usr/share/nginx/html

