FROM node:10-alpine
ADD . /app
WORKDIR /app
#python
RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
    && npm install \
    && apk del .gyp
RUN npm install
#RUN pm2 start  bin/www  -i 0
ENTRYPOINT ["npm", "start"]
